site_name: 4D Systems
copyright: Copyright &copy; 2023 4D Systems

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

extra:
  generator: false

nav:
  - Home: index.md
  - Document 1: doc_1/index.md
  - Document 2: doc_2/index.md
  - Document 3: doc_3/index.md
  - Document 4: doc_4/index.md
  - Document 5:
    - Document 5.1: doc_5/index.md
    - Document 5.2: doc_5/index.md
    - Document 5.3: doc_5/index.md
    - Document 5.4: doc_5/index.md
  - Document 6: doc_6/index.md
  - Document 7: doc_7/index.md
  - Document 8: doc_8/index.md
  - Document 9: doc_9/index.md
  - Document 10: doc_10/index.md

theme:
  name: material
  custom_dir: overrides
  logo: img/logo_4DSystems.png
  favicon: img/logo_4DSystems.png
  font:
    text: Barlow
  palette:
    # Palette toggle for light mode
    # - scheme: default
    primary: custom
    accent: custom
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: custom
    #   accent: custom
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow

plugins:
  - search
  - tags

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: Table of Contents
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
